[package]
name = "append_only_updates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
bytes = "*"
uuid = { version = "*", features = ["v4", "v7"] }
rand = { version = "0.8" }
serde = { version = "*", features = ["derive"] }
bincode = "*"
memmap2 = "*"
tracing = "*"

[dev-dependencies]
tempdir = { version = "*" }
